version: '2'

jobs:
  checkout:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./

  psr4:
    docker:
      - image: circleci/php
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - vendor-v1-psr4-{{ checksum "composer.json" }}
      - run:
          name: Composer install
          command: composer install --no-progress --no-interaction
      - save_cache:
          key: vendor-v1-psr4-{{ checksum "composer.json" }}
          paths:
            - vendor
            - composer.lock
      - run:
          name: Check PSR4 standards
          command: composer check-style

  php74:
    docker:
      - image: circleci/php:7.4
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - vendor-v1-php74-{{ checksum "composer.json" }}
      - run:
          name: Composer install
          command: composer install --no-progress --no-interaction
      - save_cache:
          key: vendor-v1-php74-{{ checksum "composer.json" }}
          paths:
            - vendor
            - composer.lock
      - run:
          name: Composer test
          command: composer test -- --coverage-text
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./

php8:
    docker:
      - image: circleci/php:8.0
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - vendor-v1-php80-{{ checksum "composer.json" }}
      - run:
          name: Composer install
          command: composer install --no-progress --no-interaction
      - save_cache:
          key: vendor-v1-php80-{{ checksum "composer.json" }}
          paths:
            - vendor
            - composer.lock
      - run:
          name: Composer test
          command: composer test -- --coverage-text
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  
workflows:
  version: 2
  tests:
    jobs:
      - checkout
      - psr4:
          requires:
            - checkout
      - php74:
          requires:
            - checkout
      - php8:
          requires:
            - checkout
